credentials:
  usernames: {}

cookie:
  expiry_days: 30
  key: "some_signature_key"
  name: "finance_dashboard_cookie"

settings:
  debug: false
  auth_required: true

logging:
  level: "INFO"
  format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>" 