[browser]
gatherUsageStats = false

[server]
runOnSave = true

[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[ui]
hideTopBar = false

# Hide the main app page from the sidebar
[pages]
hideFirstPage = true 